### ISSUE TITLE
Leapp preupgrade report failed

### ISSUE THREAD

**Issue by adpavlov** [redhat-cop/infra.leapp#142]
Playbook:

```
- name: Analysis
  hosts: '*10.61.17.53'
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_preupg_opts: '--target 8.8'
    leapp_answerfile: |
      [remove_pam_pkcs11_module_check]
      confirm = True
  tasks:
    - name: Generate preupgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis
```
OS release
```
cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

Role is failing on Leapp usage syntax:

`invalid choice: '8.8' (choose from '9.3')`
```
cat /var/log/ripu/ripu.log
RIPU preupgrade analysis
Job started at 2023-12-07T15:11:29Z
usage: leapp preupgrade [-h] [--nogpgcheck]
                        [--report-schema {1.0.0,1.1.0,1.2.0}] [--target {9.3}]
                        [--iso ISO] [--channel {ga,tuv,e4s,eus,aus}]
                        [--enablerepo <repoid>] [--no-rhsm-facts]
                        [--no-insights-register] [--no-rhsm] [--verbose]
                        [--debug] [--whitelist-experimental ActorName]

Description:

Generate preupgrade report

Optional arguments:
  -h, --help            show this help message and exit
  --nogpgcheck          Disable RPM GPG checks. Same as yum/dnf --nogpgcheck
                        option.
  --report-schema {1.0.0,1.1.0,1.2.0}
                        Specify report schema version for leapp-report.json
  --target {9.3}        Specify RHEL version to upgrade to for default
                        detected upgrade flavour
  --iso ISO             Use provided target RHEL installation image to perform
                        the in-place upgrade.
  --channel {ga,tuv,e4s,eus,aus}
                        Set preferred channel for the IPU target.
  --enablerepo <repoid>
                        Enable specified repository. Can be used multiple
                        times.
  --no-rhsm-facts       Do not store migration information using Red Hat
                        Subscription Manager. Automatically implied by --no-
                        rhsm.
  --no-insights-register
                        Do not register into Red Hat Insights
  --no-rhsm             Use only custom repositories and skip actions with Red
                        Hat Subscription Manager
  --verbose             Enable verbose logging
  --debug               Enable debug mode
  --whitelist-experimental ActorName
                        Enables experimental actors
error: argument --target: invalid choice: '8.8' (choose from '9.3')
Job ended at 2023-12-07T15:12:46Z
```
