### ISSUE TITLE
Repeatedly running the analysis role with different local_repos_leapp variables can give unexpected results

### ISSUE THREAD

**Issue by rjo-uk** [redhat-cop/infra.leapp#225]
Repeatedly running the analysis role with different `local_repos_leapp` variables can result in unwanted repositories in `/etc/leapp/files/leapp_upgrade_repositories.repo` due to the fact that `/etc/leapp/files/leapp_upgrade_repositories.repo` is not populated from scratch on each analysis run.

Consider the following example:

We run the analysis role on servers in different environments, each of which have different repository servers and naming conventions.  We use the `leapp_upgrade_type: custom` option and specific repo details in `local_repos_leapp`.

Sample playbook and variables:

play.yml
```
---
- name: Run IPU Analysis
  hosts: all
  roles:
    - infra.leapp.analysis
```

leapp_vars.yml
```
leapp_upgrade_type: custom
local_repos_leapp:
  - name: london-rhel-8-for-x86_64-baseos-rpms
    description: Red Hat 8.10 Base OS
    baseurl: http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
  - name: london-rhel-8-for-x86_64-appstream-rpms
    description: Red Hat 8.10 App Stream
    baseurl: http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
```

Run the playbook for the first time on a new server:

`ansible-playbook play.yml -e @leapp_vars.yml`

On the client, `/etc/leapp/files/leapp_upgrade_repositories.repo` is created as expected:

```
[london-rhel-8-for-x86_64-baseos-rpms]
baseurl = http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 Base OS

[london-rhel-8-for-x86_64-appstream-rpms]
baseurl = http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 App Stream
```

Some time later, our analysis shows that the repository configuration was invalid (for example we need to change the repository server from 'london' to 'nyc').  As such we update `leapp-vars.yml` and change the `name` and `baseurl` fields:

```
leapp_upgrade_type: custom
local_repos_leapp:
  - name: nyc-rhel-8-for-x86_64-baseos-rpms
    description: Red Hat 8.10 Base OS
    baseurl: http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
  - name: nyc-rhel-8-for-x86_64-appstream-rpms
    description: Red Hat 8.10 App Stream
    baseurl: http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
```

We run the analysis playbook again:

`ansible-playbook play.yml -e @leapp_vars.yml`

Expected behaviour:

`/etc/leapp/files/leapp_upgrade_repositories.repo` contains ONLY our new 'nyc' repositories:

```
[nyc-rhel-8-for-x86_64-baseos-rpms]
baseurl = http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 Base OS

[nyc-rhel-8-for-x86_64-appstream-rpms]
baseurl = http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 App Stream
```

Actual behaviour:

`/etc/leapp/files/leapp_upgrade_repositories.repo` contains the unwanted 'london' repositories from the previous run:
```
[london-rhel-8-for-x86_64-baseos-rpms]
baseurl = http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 Base OS

[london-rhel-8-for-x86_64-appstream-rpms]
baseurl = http://repo01.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 App Stream

[nyc-rhel-8-for-x86_64-baseos-rpms]
baseurl = http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 Base OS

[nyc-rhel-8-for-x86_64-appstream-rpms]
baseurl = http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
enabled = 1
gpgcheck = 0
name = Red Hat 8.10 App Stream
```

This has an unwanted behaviour if analysis is run multiple times with various repository configurations - invalid repos are left behind.

One solution might be to remove `/etc/leapp/files/leapp_upgrade_repositories.repo`at the end of the analysis run.  Another solution would be to empty `/etc/leapp/files/leapp_upgrade_repositories.repo` before populating it in the existing task.

Also note that the same variable and approach and variable used in the upgrade role.

**Comment by djdanielsson** [comment]
ok looking at the code you can set London to absent state and it will remove it

**Comment by djdanielsson** [comment]
correct

**Comment by nickhardiman** [comment]
I'd say, for /etc/repos.d/, adding and removing repo files is common. Changing repo files is rare. My expectation is this would be the same - I specify repo file content, not changes.

**Comment by rjo-uk** [comment]
Now that I understand how the repository fragments in `leapp_upgrade_repositories.repo` are created, I will use a different approach in my playbook without needing to modify the role.

For my use case, I can't guarantee that content in `/etc/leapp/files/leapp_upgrade_repositories.repo` has been pre-populated via a previous run of the analysis role and/or I know all of the repositories that need to be removed in that file.

A simpler playbook could look like this:

```
---
- name: Run IPU Analysis
  hosts: all
  vars:
    leapp_upgrade_type: custom
    local_repos_leapp:
      - name: nyc-rhel-8-for-x86_64-baseos-rpms
        description: Red Hat 8.10 Base OS
        baseurl: http://nyc.example.com/8.10/rhel-8-for-x86_64-baseos-rpms
      - name: nyc-rhel-8-for-x86_64-appstream-rpms
        description: Red Hat 8.10 App Stream
        baseurl: http://nyc.example.com/8.10/rhel-8-for-x86_64-appstream-rpms

  pre_tasks:
    - name: Ensure /etc/leapp/files/leapp_upgrade_repositories.repo does not exist
      ansible.builtin.file:
        path: /etc/leapp/files/leapp_upgrade_repositories.repo
        state: absent

  roles:
    - infra.leapp.analysis
```

In the above example, this guarantees that only `nyc-rhel-8-for-x86_64-baseos-rpms` and `nyc-rhel-8-for-x86_64-appstream-rpms` end up in `/etc/leapp/files/leapp_upgrade_repositories.repo`.

As part of this discussion, we did encounter a potential change to allow for removal of specific repos.  I am happy to make a PR to change https://github.com/redhat-cop/infra.leapp/blob/9dcb2e99faff8eebfdd29f15d39be9bf47e8f2e5/roles/analysis/tasks/analysis-leapp.yml#L60

to

```state: "{{ item.state | default(present) }}"```

@djdanielsson / @swapdisk let me know if you would like such a PR?
