### ISSUE TITLE
[RFE] Support upgrade from RHEL 9 to 10

### ISSUE THREAD

**Issue by swapdisk** [redhat-cop/infra.leapp#236]
As announced [here](https://www.redhat.com/en/blog/red-hat-enterprise-linux-10-beta-now-available), RHEL 10 Beta is now available and "mid-2025" is the target date for GA release.

To prepare for this, let's start working on making the roles support upgrades from RHEL 9 to 10. For now, these upgrades would target RHEL 10 Beta just for testing and demonstration use, but the ultimate goal is to be ready on day one after the RHEL 10 GA release.

This work will happen under the [rhel_9_to_10](https://github.com/swapdisk/infra.leapp/tree/rhel_9_to_10) branch of my infra.leapp fork. If you are interested in contributing, I'll happily review your pull requests there!

We'll be posting updates on the progress under this issue. The first big milestone with be to document here how to try it out when we have something reasonably ready for testing.

Cheers!

**Comment by swapdisk** [comment]
Amazingly, only very minor changes required to make the collection roles work for upgrading from RHEL 9 to 10. See diff under commit 63de95526af1be1985cb7695f91327504a638901 on my rhel_9_to_10 branch.

That's the good news. The bad news is that testing Leapp upgrades is not in scope for RHEL 10 Beta as the required Leapp packages are not GA in the RHEL 9 repos. Because of this, I had to do some kludgy acrobatics to demonstrate infra.leapp doing an upgrade from RHEL 9 to RHEL 10. 

What follows are the steps I used to get to RHEL 10 using my rhel_9_to10 branch of the collection. Keep in mind that while upgrade play run is "failed" and the resulting RHEL 10 host is not perfect, the point here is not testing Leapp itself, but rather testing that the Ansible automation gets Leapp to do what it will. This upgrade "fails" the same way if you do the same manually.

The first step is to get yourself a RHEL 9 instance to upgrade. I used [Insights image builder](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/creating_customized_images_by_using_insights_image_builder/index) to create a VM on my laptop with a vanilla 9.5 install subscribed to Red Hat repos. Just for fun, I included the `@web-server` package group in my blueprint which led to an issue that I'll explain further down.

When you have your RHEL 9 host ready to test, the next step is to run an analysis job. My first try at this failed because there are no Leapp packages yet in the RHEL 9 repos. So to get around that, I used the Leapp packages available in CentOS Stream 9 repos. The next challenge was getting Leapp to find the RHEL 10 packages. I gave up trying to make it work using the RHEL 10 Beta repos on the Red Hat CDN and decided to try using CentOS Stream 10 repos instead. This is the playbook I used to automate all that for a successful analysis play:

```
---
- name: Analysis
  hosts: happy-bmader
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_upgrade_type: custom
    analysis_repos_el9: centos-stream-9-appstream-rpms
    local_repos_pre_leapp:
      - name: centos-stream-9-appstream-rpms
        description: CentOS Stream 9 for x86_64 - AppStream (RPMs)
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256
        baseurl: https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/
        enabled: false
        gpgcheck: true
    local_repos_leapp:
      - name: centos-stream-10-baseos-rpms
        description: CentOS Stream 10 for x86_64 - BaseOS (RPMs)
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256
        baseurl: https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/
        gpgcheck: true
      - name: centos-stream-10-appstream-rpms
        description: CentOS Stream 10 for x86_64 - AppStream (RPMs)
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256
        baseurl: https://mirror.stream.centos.org/10-stream/AppStream/x86_64/os/
        gpgcheck: true

  roles:
    - infra.leapp.analysis
...
```

Here's the log output from the new task I added to install the RHEL 9 Leapp packages: 

```
TASK [infra.leapp.analysis : analysis-leapp | Install packages for preupgrade analysis on RHEL 9] ***
changed: [happy-bmader] => {
  "changed": true,
  "msg": "",
  "rc": 0,
  "results": [
    "Installed: leapp-0.18.0-4.el9.noarch",
    "Installed: leapp-deps-0.18.0-4.el9.noarch",
    "Installed: leapp-upgrade-el9toel10-0.21.0-4.el9.noarch",
    "Installed: leapp-upgrade-el9toel10-deps-0.21.0-4.el9.noarch",
    "Installed: python3-leapp-0.18.0-4.el9.noarch",
    "Installed: libdb-utils-5.3.28-54.el9.x86_64",
    "Installed: systemd-container-252-46.el9_5.2.x86_64"
  ]
}
```

The analysis job finished successfully, so I checked `/var/log/leapp/leapp-report.txt` on the host. Much to my surprise, there were no inhibitors listed. Having no inhibitors, the next step is to try an upgrade job. Remember, "fail fast" and then have coffee!

Well, I hit a few more issues before getting an upgrade to go through all the way. The first was because I had included the `@web-server` group in my image builder blueprint. This installs the `httpd` and related packages including the `redhat-logos-httpd` package. The latter broke the upgrade transaction because we're using CentOS Stream 10 repos and there is no package by that name due to branding differences. No problem, `dnf -y remove redhat-logos-httpd` command and try again.

I also hit upgrade transaction breakage because of differences with how the `/usr/lib64/ossl-modules/fips.so` library is packaged. In CentOS Stream, it's provided by the `openssl-libs` package, but the same library is provided by separate packages with RHEL. I think it has something to do with the legalities of FIPS certification, so we can thank the US Government for this one. The solution was to exclude those separate packages from the Leapp transaction. You can see how I did that with pre_tasks in the upgrade playbook I ultimately got working:

```
---
- name: Upgrade
  hosts: happy-bmader
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_upgrade_type: custom
    local_repos_leapp:
      - name: centos-stream-10-baseos-rpms
        description: CentOS Stream 10 for x86_64 - BaseOS (RPMs)
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256
        baseurl: https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/
        gpgcheck: true
      - name: centos-stream-10-appstream-rpms
        description: CentOS Stream 10 for x86_64 - AppStream (RPMs)
        gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256
        baseurl: https://mirror.stream.centos.org/10-stream/AppStream/x86_64/os/
        gpgcheck: true

  pre_tasks:
    - name: Hack packaging quirk with CentOS openssl
      ansible.builtin.lineinfile:
        path: /etc/leapp/transaction/to_remove
        line: "{{ item }}"
      loop:
        - openssl-fips-provider
        - openssl-fips-provider-so

  roles:
    - infra.leapp.upgrade
...
```

Using this playbook, the run successfully executed the Leapp upgrade and the host came up on a RHEL 10 kernel. However, because we used CentOS Stream rather than genuine RHEL repos, the `redhat-release` package did not get updated. Again, a case of no such package name because of branding differences. This led to the play failing at the "Validate current OS major version" task: 

```
TASK [infra.leapp.upgrade : upgrade-validation | Validate current OS major version] ***
fatal: [happy-bmader]: FAILED! => {
    "assertion": "ansible_distribution_major_version == rhel_dest_major_version",
    "changed": false,
    "evaluated_to": false,
    "msg": "Expected leapp destination OS major version 10 but OS major version is 9."
}
```

This validation check fails because Ansible fact `distribution_major_version` still reports OS version 9 based on the stale information in the `/etc/os-release` file. But rest assured, the `last` command provides proof of the successful upgrade:

```
[root@happy-bmader ~]# last -w reboot
reboot   system boot  6.12.0-37.el10.x86_64 Wed Jan  8 09:58   still running
reboot   system boot  6.12.0-37.el10.x86_64 Wed Jan  8 09:57 - 09:58  (00:00)
reboot   system boot  5.14.0-503.21.1.el9_5.x86_64 Wed Jan  8 09:28 - 09:41  (00:13)
reboot   system boot  5.14.0-503.19.1.el9_5.x86_64 Wed Jan  8 08:51 - 09:27  (00:36)

wtmp begins Wed Jan  8 08:51:02 2025
```

So where does that leave us. Certainly, the actual OS upgrade is kind of a mess, but we did learn that with only some minor changes, the infra.leapp collection will be able to handle Leapp upgrades from RHEL 9 to 10 when Red Hat makes the support for that GA.

Thanks for riding along. 

Cheers!

**Comment by swapdisk** [comment]
Amazingly, only very minor changes required to make the collection roles work for upgrading from RHEL 9 to RHEL 10 Beta. See the diff under commit 63de95526af1be1985cb7695f91327504a638901 on my rhel_9_to_10 branch.

What follows are the steps that worked for me to get to RHEL 10 Beta using the rhel_9_to10 branch of the collection. There were a some minor issues requiring a couple of sneaky extra tasks in my test playbooks, but we have demonstrated a successful RHEL 10 upgrade using Ansible automation and the infra.leapp collection.

The first step is we need to get a RHEL 9 instance to upgrade. I used [Insights image builder](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/creating_customized_images_by_using_insights_image_builder/index) to create a VM on my laptop with a vanilla 9.5 install automatically subscribed to Red Hat repos. You could also install RHEL 9 using an ISO, but it will need to be registered using subscription-manager for this to work.

When you have your RHEL 9 host ready to test, the next step is to run an analysis job. Unfortunately, there are no Leapp packages yet in Red Hat's RHEL 9 GA repos. So to get around that, we are using the "beta" Leapp packages available from the public upstream COPR repo for Leapp. You can see how I configured that repo in the playbook I used to automate my analysis job:

```
---
- name: Analysis
  hosts: sweet-bmader
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_upgrade_type: cdn
    leapp_env_vars:
      LEAPP_UNSUPPORTED: 1
      LEAPP_DEVEL_DATABASE_SYNC_OFF: 1
      LEAPP_DEVEL_TARGET_PRODUCT_TYPE: beta

  pre_tasks:
    - name: Configure upstream COPR repository for Leapp
      ansible.builtin.get_url:
        url: https://copr.fedorainfracloud.org/coprs/g/oamg/leapp/repo/epel-9/group_oamg-leapp-epel-9.repo
        dest: /etc/yum.repos.d/oamg.repo
        mode: '0644'

  roles:
    - infra.leapp.analysis
...
```

You can see we also configured some env vars for the Leapp run. Setting `LEAPP_DEVEL_DATABASE_SYNC_OFF=1` is convenient for testing as it makes Leapp run faster. The `LEAPP_DEVEL_TARGET_PRODUCT_TYPE=beta` setting is required to inform Leapp to use the RHEL 10 Beta repos for the upgrade. Finally, `LEAPP_UNSUPPORTED=1` is required to acknowledge that using LEAPP_DEVEL_* vars is not supported. Continue at your own risk!

Here's the log output from the new task added in the rhel_9_to_10 branch of the analysis role to install the RHEL 9 Leapp packages:

```
TASK [infra.leapp.analysis : analysis-leapp | Install packages for preupgrade analysis on RHEL 9] ***
changed: [sweet-bmader] => {
  "changed": true,
  "msg": "",
  "rc": 0,
  "results": [
    "Installed: leapp-0.18.0-100.20250108212821781602.main.7.g52cd433.el9.noarch",
    "Installed: leapp-upgrade-el9toel10-0.21.0-100.20250109205304713680.main.44.gc92dbb41.el9.noarch",
    "Installed: leapp-deps-0.18.0-100.20250108212821781602.main.7.g52cd433.el9.noarch",
    "Installed: libdb-utils-5.3.28-54.el9.x86_64",
    "Installed: leapp-upgrade-el9toel10-deps-0.21.0-100.20250109205304713680.main.44.gc92dbb41.el9.noarch",
    "Installed: systemd-container-252-46.el9_5.2.x86_64",
    "Installed: python3-leapp-0.18.0-100.20250108212821781602.main.7.g52cd433.el9.noarch"
  ]
}
```

The analysis job finished successfully, so let's check /var/log/leapp/leapp-report.txt on the host. Much to my surprise, there were no inhibitors listed. Having no inhibitors, the next step is to try an upgrade job. Remember, "fail fast" and then have coffee!

Here we hit an issue where the SHA1 rpm signing public keys in the RHEL 9 image are incompatible with upgrading to RHEL 10. This is a known issue and the Leapp team is working in fixing it under private bug [RHEL-71517](https://issues.redhat.com/browse/RHEL-71517). In the meantime, we can get around the issue by manually importing the SHA256 generation of the keys. Of course, we can easily automate this fix as seen in my test playbook for running the upgrade:

```
---
- name: Upgrade
  hosts: sweet-bmader
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_upgrade_type: cdn
    leapp_env_vars:
      LEAPP_UNSUPPORTED: 1
      LEAPP_DEVEL_DATABASE_SYNC_OFF: 1
      LEAPP_DEVEL_TARGET_PRODUCT_TYPE: beta

  pre_tasks:
    - name: Workaround for rpm gpg-pubkey issue
      ansible.builtin.shell: |
        /bin/cp /var/lib/leapp/el10userspace/etc/pki/rpm-gpg/* /etc/pki/rpm-gpg/
        /bin/rpm -e gpg-pubkey-fd431d51-4ae0493b
        /bin/rpm -e gpg-pubkey-f21541eb-4a5233e8
        /bin/rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        /bin/rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta

  roles:
    - infra.leapp.upgrade
...
```

Using this playbook, the run successfully executed the Leapp upgrade and our host came up running a RHEL 10 kernel. These commands provides our proof of the successful upgrade:

```
[root@sweet-bmader ~]# last -w reboot
reboot   system boot  6.11.0-0.rc5.23.el10.x86_64 Fri Jan 10 12:19   still running
reboot   system boot  6.11.0-0.rc5.23.el10.x86_64 Fri Jan 10 12:19 - 12:19  (00:00)
reboot   system boot  5.14.0-503.21.1.el9_5.x86_64 Fri Jan 10 12:06 - 12:15  (00:09)
reboot   system boot  5.14.0-503.19.1.el9_5.x86_64 Fri Jan 10 10:31 - 12:06  (01:35)

wtmp begins Fri Jan 10 10:31:00 2025
[root@sweet-bmader ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 10.0 Beta (Coughlan)
[root@sweet-bmader ~]# dnf repolist
Updating Subscription Management repositories.

This system is registered with an entitlement server, but is not receiving updates. You can use subscription-manager to assign subscriptions.

repo id                                         repo name
copr:copr.fedorainfracloud.org:group_oamg:leapp Copr repo for leapp owned by @oamg
rhel-10-for-x86_64-appstream-beta-rpms          Red Hat Enterprise Linux 10 for x86_64 - AppStream Beta (RPMs)
rhel-10-for-x86_64-baseos-beta-rpms             Red Hat Enterprise Linux 10 for x86_64 - BaseOS Beta (RPMs)
```

So where does that leave us. Yes, we had to fiddle with a couple fun Leapp issues, but hey, it's beta. The good news is we learned that with only some minor changes, the infra.leapp collection will be able to handle Leapp upgrades from RHEL 9 to 10 when Red Hat makes the support for that GA.

Thanks for riding along.

Cheers!
